# Generated by Django 5.1.2 on 2024-10-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_region_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название терминала')),
                ('address', models.TextField(verbose_name='Адрес терминала')),
                ('get', models.DateField(verbose_name='Дата получения')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Терминал',
                'verbose_name_plural': 'Терминалы',
            },
        ),
    ]
