# Generated by Django 5.1.2 on 2024-10-22 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='get',
            field=models.DateField(verbose_name='Дата последнего сбора'),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='core.region', verbose_name='Регион'),
        ),
    ]
