# Generated by Django 5.1.2 on 2024-10-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_terminal_get_alter_terminal_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='ks', max_length=255),
            preserve_default=False,
        ),
    ]
