# Generated by Django 5.1.2 on 2024-10-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='terminals/', verbose_name='Фото здания терминала'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
