# Generated by Django 5.1.2 on 2024-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_terminal_photo_alter_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='collection_interval',
            field=models.IntegerField(default=1, verbose_name='Интервал сбора (в днях)'),
        ),
    ]
