# Generated by Django 5.1.2 on 2024-10-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_terminal_collection_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='collection_interval',
        ),
        migrations.AddField(
            model_name='terminal',
            name='interval',
            field=models.PositiveIntegerField(default=1, verbose_name='Интервал сбора (дней)'),
        ),
    ]
