# Generated by Django 5.1.2 on 2024-11-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_terminal_get_remove_terminal_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incassation',
            name='next_collection',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей инкассации'),
        ),
    ]
