# Generated by Django 5.1.2 on 2024-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_incassation_next_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incassation',
            name='next_collection',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей инкассации'),
        ),
    ]
